#pragma once

#include "motor/IMotorDriver.hpp"

#include <atomic>
#include <mutex>
#include <thread>

struct gpiod_chip;
struct gpiod_line_request;

/**
 * @brief Differential-drive motor driver implemented with libgpiod v2.
 *
 * Direction pins are driven through libgpiod output lines. PWM is generated by
 * a dedicated thread using timerfd + eventfd so that blocking I/O wakes the
 * worker instead of busy waiting.
 */
class GpiodMotorDriver final : public IMotorDriver {
public:
    /**
     * @brief Motor pin assignment in BCM numbering.
     */
    struct Pins {
        int PWMA;
        int AIN1;
        int AIN2;
        int PWMB;
        int BIN1;
        int BIN2;
    };

    explicit GpiodMotorDriver(Pins pins,
                              int pwmRange = 100,
                              int pwmFrequencyHz = 200,
                              const char* chipPath = "/dev/gpiochip0");
    ~GpiodMotorDriver() override;

    GpiodMotorDriver(const GpiodMotorDriver&) = delete;
    GpiodMotorDriver& operator=(const GpiodMotorDriver&) = delete;

    void setLeft(int speed, bool forward) override;
    void setRight(int speed, bool forward) override;
    void stopAll() override;

private:
    struct MotorState {
        int speed{0};
        bool forward{true};
    };

    void configureOutputs(const char* chipPath);
    void pwmLoop();
    void setDirectionUnsafe(bool left, bool forward);
    void setPwmLevelUnsafe(bool left, bool high);
    void notifyPwmWorker();
    void stopPwmThread();
    static int clampSpeed(int speed);

    Pins pins_{};
    int pwmRange_{100};
    int pwmFrequencyHz_{200};

    gpiod_chip* chip_{nullptr};
    gpiod_line_request* request_{nullptr};

    std::mutex mutex_;
    MotorState left_{};
    MotorState right_{};

    std::atomic<bool> pwmRunning_{false};
    std::thread pwmThread_;
    int pwmTimerFd_{-1};
    int pwmEventFd_{-1};
    int pwmEpollFd_{-1};
};
